version: '2'
services:
  main:
    command: 'npm run debug'
    ports:
        - 9228:9228
    environment:
        - CONSUMER_GROUP_ID=alpha
    expose:
        - 9228
    volumes:
        - ./coverage:/home/node/event-client/coverage
        - ./src:/home/node/event-client/src
        - ./test:/home/node/event-client/test
        - ./local:/home/node/event-client/local
        - ./wiki:/home/node/event-client/wiki
