version: '2'
services:
  main:
    command: 'npm run debug'
    ports:
        - 9230:9230
    environment:
        - CONSUMER_GROUP_ID=alpha
    expose:
        - 9230
    volumes:
        - ./package.json:/home/node/event-client/package.json
        - ./coverage:/home/node/event-client/coverage
        - ./src:/home/node/event-client/src
        - ./test:/home/node/event-client/test
        - ./local:/home/node/event-client/local
        - ./wiki:/home/node/event-client/wiki
