version: '2'
services:
    main:
        build: .
        depends_on:
            - registrator
            - rabbit2
            - consul
        environment:
            RABBITMQ_USER: $RABBITMQ_USER
            RABBITMQ_PASS: $RABBITMQ_PASS

    rabbit1:
        image: opuscapita/rabbitmq:dev
        hostname: rabbit1
        ports:
            - '4369:4369'
            - '5671:5671'
            - '5672:5672'
            - '15672:15672'
            - '25672:25672'
            - '6666:6666'
        environment:
            RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
            SERVICE_5672_NAME: 'rabbitmq-amqp'
            RABBITMQ_ERLANG_COOKIE: $RABBITMQ_ERLANG_COOKIE
            KILL_PORT: 6666
        depends_on:
            - consul

    rabbit2:
        image: opuscapita/rabbitmq:dev
        hostname: rabbit2
        ports:
            - '4370:4369'
            - '5673:5671'
            - '5674:5672'
            - '15673:15672'
            - '25673:25672'
            - '6667:6666'
        environment:
            RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
            SERVICE_5672_NAME: 'rabbitmq-amqp'
            RABBITMQ_ERLANG_COOKIE: $RABBITMQ_ERLANG_COOKIE
            KILL_PORT: 6666
            CLUSTER_WITH: 'rabbit1'
        # command: ["/wait-for", "rabbit1:5672", "--", "rabbitmq-server"]
        depends_on:
            - rabbit1
            - consul

    registrator:
        image: gliderlabs/registrator
        command: -internal consul://consul:8500
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        depends_on:
            - consul
        restart: on-failure

    consul:
        image: consul:1.4
        ports:
            - '8400:8400'
            - '8500:8500'
            - '8600:53/udp'
        labels:
            SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
        command: [agent, '-server', '-ui', '-bootstrap', '-client=0.0.0.0']
