version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Preparing
          command: |
            mkdir -p coverage
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            git config --global user.email "${GIT_USER_EMAIL}"
            git config --global user.name "${GIT_USER_NAME}"
            git clone https://github.com/OpusCapita/event-client.wiki.git wiki
      - run:
          name: Testing
          command: |
            docker-compose build --no-cache
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run main npm run test
            docker-compose -f docker-compose.yml -f docker-compose.ci.yml run main npm run test-coverage
      - store_artifacts:
          path: ./test/test-results.xml
      - deploy:
          name: Publishing to NPM...
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker-compose -f docker-compose.yml -f docker-compose.ci.yml run main npm run doc
              cd wiki && git add . && git commit -m 'Updated documentation' && git push ; cd .. && rm -Rf wiki
              git reset HEAD --hard
              echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
              npm publish
              npm run upload-coverage
              git push --set-upstream origin master
            fi
